name: Python Artifact Example

on:
  push:
    branches: [ main ]

jobs:
  generate-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run app.py to generate output 
        run: |
          cd artifacts
          python3 app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-file
          path: artifacts/output.txt

  use-output:
    needs: generate-output
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: result-file
          path: artifacts

      - name: Show artifact content
        run: cat artifacts/output.txt 
